/** Dostępne awatary piłkarskie przy rejestracji (jak w Flask). */
export const ALL_PLAYERS = [
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Kylian Mbappé",
  "Neymar",
  "Robert Lewandowski",
  "Kevin De Bruyne",
  "Erling Haaland",
  "Luka Modrić",
  "Karim Benzema",
  "Mohamed Salah",
  "Vinicius Jr",
  "Pedri",
  "Gavi",
  "Antoine Griezmann",
  "Harry Kane",
  "Bukayo Saka",
  "Phil Foden",
  "Jude Bellingham",
  "Sergio Ramos",
  "Alisson Becker",
  "Thibaut Courtois",
  "Marc ter Stegen",
  "Virgil van Dijk",
  "Antonio Rüdiger",
  "Joshua Kimmich",
  "Heung-min Son",
  "Raheem Sterling",
  "Paulo Dybala",
  "Ángel Di María",
  "Martin Ødegaard",
];

export const SESSION_COOKIE = "awp_session";
